parser: babel-eslint
extends: airbnb
rules:
  comma-dangle: 'off'
  react/forbid-prop-types: 'off'
  react/no-array-index-key: 'off'
  jsx-a11y/no-static-element-interactions: 'off'
  import/extensions: 'off'
  import/first: 'off'
settings:
  import/resolver: eslint-import-resolver-webpack
